trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TESTING: "1"

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest flake8
  displayName: Install dependencies

- script: |
    flake8 app
  displayName: Lint code

- script: |
    export TESTING=1
    pytest -q
  displayName: Run tests